# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SoftPillow.
email: info@softpillow.me
description: > # this means to ignore newlines until "baseurl:"
  We like to build great code, and we'd like to tell you about it
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# icon
icon-16x16: assets/images/icon/softpillow_favicon.ico
icon-32x32: assets/images/icon/softpillow_favicon.ico
# theme color
theme-color: { 
  default-color: main-frame-color,
  header-color: gradient-bg,
  home-color:  main-frame-color,
  about-color: gradient-bg,
  archive-color: gradient-bg,
  links-color: white,
  tags-color: blue
} 
## mobile nav
mobile-hp:
mobile-bg:

# header 背景图片
header-bg: /assets/images/bg.png


# cdn
cdn: false
cdnurl: https://jekyll-materialize.b0.upaiyun.com/

#google_analytics
google_analytics:

# todd

defaultAuthor: SoftPillow.
defaultAuthorImage: assets/images/icon/sofpillow_favicon.ico
manyAuthors: true

# gallery
gallery: false

# Build settings
markdown: kramdown

exclude: [vendor]
